document.write(""
+"<base target='_top'>"
+"<META http-equiv='content-type' content='text/html; charset=EUC-KR'>"
+"<link rel='stylesheet' href='http://img.hani.co.kr/section-image/member/style_copyright.css' type='text/css'>"

+"<table border='0' cellspacing='0' cellpadding='0'>"
+"<tr><td height='0'><div id='div_1din_ban_limit'><!-- 1단 롤링배너 bottom limit 지정  --></div></td></tr>"
+"<tr><td height='10'></td></tr>"
+"<tr><td align='center' class='f12black' style='line-height:1.7'>"
+"	<a href='http://company.hani.co.kr'><b>한겨레신문사</b></a>"
+"	<font color='#959595'>|</font>"
+"	<a href='http://nuri.hani.co.kr/customer/customer_main.html'>구독신청</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"  <a href='#' onClick=\"javascript:window.open('http://contribute.hani.co.kr/input/hankisa.hani','','width=630, height=550, scrollbars=1, resizable=1')\">제보</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='#' onClick=\"javascript:window.open('http://contribute.hani.co.kr/input/hantogo.hani','','width=630, height=690, scrollbars=1, resizable=1')\">투고</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://company.hani.co.kr/sp?pname=advertisement.index&spname=advertisement_01_01'>지면광고</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://company.hani.co.kr/sp?pname=advertisement.index&spname=advertisement_03_01'>온라인광고</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://company.hani.co.kr/sp?pname=advertisement.index&spname=advertisement_03_01'>사업제휴</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://company.hani.co.kr/sp?pname=recruit.index&spname=recruit_01_02'>채용</a>"

+"	<hr size='1' color='#EBEBEB'>"

+"	<font class='f12gray'><a href='http://bridge.hani.co.kr/login/mypage_copyright.jsp?site=hani'>저작권안내</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<font class='f12gray'><a href='http://bridge.hani.co.kr/login/member_accept.jsp?site=hani'>회원약관</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://bridge.hani.co.kr/login/mypage_private.jsp?site=hani'>개인정보 취급방침</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://bridge.hani.co.kr/login/mypage_brainy.jsp?site=hani'>지적재산 보호정책</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://bridge.hani.co.kr/login/mypage_email.jsp?site=hani'>이메일주소 무단수집거부</a>"
+"	<img src='http://img.hani.co.kr/section-image/member/copy_line_3.gif' hspace='3'>"
+"	<a href='http://www.hani.co.kr/common/sitemap/sitemap.html'>사이트맵</a></font>"
+"    </td>"
+"</tr>"
+"<tr><td height='5'></td></tr>"
+"<tr><td align='center'><font class='f11gray'>copyright The Hankyoreh</font></td></tr>"
+"<tr><td height='10'></td></tr>"
+"</table>"
);