document.write ('<SCRIPT LANGUAGE="JavaScript"> \n');
document.write ('\n');
document.write ('<!-- \n');
document.write ('\n');
document.write ('var rmad_URL = "http://img.hani.co.kr/adimg/shape_090921/shapepopup_hani.js"; \n');
document.write ('var TI_movie_objid = "shape";\n');
document.write ('\n');
document.write ('var TI_movie_url = "http://img.hani.co.kr/adimg/citicpa_110421/citiclear_110418_400300.swf";\n');
document.write ('\n');
document.write ('var TI_movie_width = "400";\n');
document.write ('var TI_movie_height = "300";\n');
document.write ('var TI_movie_top = "-1400";\n');
document.write ('var TI_movie_left = "730";\n');
document.write ('var TI_movie_top_FF = "-1200";\n');
document.write ('var TI_movie_left_FF= "30";\n');
document.write ('var page_width = "980";\n');
document.write ('\n');
document.write ('function ClickMovie1 (){\n');
document.write ('window.open("http://ad.hani.co.kr/RealMedia/ads/click_lx.ads/www.hani.co.kr/economy/867690358/Position3/OasDefault/citi_100903_shape/citi_110422_400300.html/37393332313531343464633738383630" ,"Newwin");\n');
document.write ('}\n');
document.write ('\n');
document.write ('\n');
document.write ('function NextMovie1 () {\n');
document.write ('document.getElementById(');
document.write ("'");
document.write ('FloatLayer1');
document.write ("'");
document.write (').style.visibility="hidden";\n');
document.write ('\n');
document.write ('}\n');
document.write ('\n');
document.write ('document.write ("<SCR" + "IPT LANG" + "UAGE=');
document.write ("'");
document.write ('JAVAS" + "CRIPT1.1');
document.write ("'");
document.write (' SRC=');
document.write ("'");
document.write ('" + rmad_URL + "');
document.write ("'");
document.write ('></SCR" + "IPT>");\n');
document.write ('\n');
document.write ('//--> \n');
document.write ('\n');
document.write ('</SCRIPT>');
