document.write ('<div id="all_wrapper1" style="position:absolute; left:0px; top:2000px; width:100%; height:0px;text-align:center; margin:0 auto;">\n');
document.write ('<div id="second_wrapper1" style="position:relative; left:0px; top:0px; text-align:left; width:'+page_width+'px; height:0px; margin:0 auto;">\n');
document.write ('<DIV ID=FloatLayer1 style="position:relative; width:' + TI_movie_width + 'px; height:' + TI_movie_height + 'px; left:'+TI_movie_left_FF+'; top:'+TI_movie_top_FF+'px; _left:'+TI_movie_left+'px; _top:'+TI_movie_top+'px; margin:0 auto; z-index:300; visibility:visible;">\n');
document.write ('<!--[if lte IE 6]><DIV ID=FloatLayerIE6 STYLE="position:relative; top:0px; left:0px;"><![endif]-->\n');
document.write ('<!--[if gte IE 7]><DIV ID=FloatLayerIE7 STYLE="position:relative; top:0px; left:0px;"><![endif]-->\n');
document.write ('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"\n');
document.write ('codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,23,0" ID=' +TI_movie_objid+ '  WIDTH=' + TI_movie_width + '  HEIGHT=' + TI_movie_height + '>\n');
document.write ('<PARAM NAME=movie VALUE="'+TI_movie_url+'">\n');
document.write ('<PARAM NAME=quality VALUE=high>\n');
document.write ('<PARAM NAME=wmode VALUE=transparent>\n');
document.write ('<PARAM NAME=bgcolor VALUE=#FFFFFF>\n');
document.write ('<PARAM NAME=allowScriptAccess VALUE=always>\n');
document.write ('<EMBED src="'+TI_movie_url+'" name=' +TI_movie_objid+ ' quality=high bgcolor=#FFFFFF WIDTH=' + TI_movie_width + ' HEIGHT=' + TI_movie_height + ' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" allowScriptAccess="always"></EMBED>\n');
document.write ('</OBJECT>\n');
document.write ('<!--[if lte IE 6]></DIV><![endif]-->\n');
document.write ('<!--[if gte IE 7]></DIV><![endif]-->\n');
document.write ('</DIV>\n');
document.write ('</DIV>\n');
document.write ('</DIV>\n');